apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-77mn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-miqv-tenant/rhtap-demo-app/hacbs-test-project-77mn@sha256:a416c9f26397ac894585bdf5153d3a0a3bbb1645e3eb060a8863b6878870a323
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
